/*
 Generated by typeshare 1.11.0
*/

export interface Plugin {
  name: string;
  description?: string;
  createdAt?: string;
  stars: number;
  topics?: string[];
  updatedAt?: string;
  url: string;
  watchers: number;
}
